### PR TITLE
Convert lpc-doc plaintext docs

### PR DESCRIPTION
**Pull request by noahgibbs**
These have been converted quickly and roughly to a combination of markdown and simple HTML. But this means we're not losing any useful documentation relative to Dworkin's lpc-doc repository. Everything should be viewable via GitHub Pages.

This PR is relative to the branch from another PR, the one that adds the architecture/layers docs. So all the commits except the last one are from that branch.

### CODE REVIEW

**Comment by ChristopherA** [comment]
All unmerged PRs need README conflcts resolved.

**Comment by ChristopherA** [comment]
Other PRs conflicts resovled, this now has 3 files conflicting.

**Comment by noahgibbs** [comment]
Yeah. This is the hard part of multiple PRs. I can base each one on the previous one (which sucks to read), or I can base them (as much as possible) all on the current head... Which means a lot of merge conflicts after one gets merged.

**Comment by ChristopherA** [comment]
Thank you.

**Pull request merged**
